#ifndef CONTRACTAPPCORE_GLOBAL_H
#define CONTRACTAPPCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTRACTAPPCORE_LIBRARY)
#  define CONTRACTAPPCORE_EXPORT Q_DECL_EXPORT
#else
#  define CONTRACTAPPCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTRACTAPPCORE_GLOBAL_H
